services:
  db:
    image: postgres:15-alpine
    container_name: banka_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
        - banka_data:/var/lib/postgresql/data
    networks:
        - banka_network

  app:
    build:
      context: .
    container_name: banka_app
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      UPLOAD_DIR: /app/uploads
    depends_on:
      - db
    networks:
      - banka_network

  nginx:
    image: nginx:alpine
    container_name: banka_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - banka_network

volumes:
  banka_data:

networks:
  banka_network:
